Incude Company in Contact
AY2324S2-CS2103T-T16-3/tp pull request #28
Opened 2024-03-14 07:04 UTC by sun-ruiheng

<img width="409" alt="Screenshot 2024-03-14 at 3 04 04 PM" src="https://github.com/AY2324S2-CS2103T-T16-3/tp/assets/60679866/81f6483c-4b4d-4bde-9560-d376fa612a14">

2024-03-15 01:08 UTC, guanquann commented
- When I entered `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague` (without the company), it did not show any change. 

- And it looks like you need to add the company prefix tag in `EditCommandParser.java`, as I can't seem to edit a person's company using `edit 7 c/ nusfishery `

2024-03-15 02:27 UTC, sun-ruiheng commented
> * When I entered `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague` (without the company), it did not show any change.
> * And it looks like you need to add the company prefix tag in `EditCommandParser.java`, as I can't seem to edit a person's company using `edit 7 c/ nusfishery `

Thanks Guan Quan,
The first bug pointed out has been fixed.
The second point is the way because Company is a compulsory field in v1.2.

2024-03-15 14:05 UTC, gavingoh99 reviewed
EditCommandParser seems to flag out empty prefixes before invalid index (> number of contacts):
edit [invalid index] n/ -> returns Name cannot be empty rather than displaying the index > number of contacts error message

2024-03-16 02:28 UTC, gavingoh99 requested changes
Currently EditCommand resets the favourite field of a contact when edited

I've provided suggestions to preserve the favourite field - do have a look!

2024-03-16 02:28 UTC, gavingoh99 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
```suggestion
    boolean updatedIsFavourite = personToEdit.getFavourite();
```

2024-03-16 02:28 UTC, gavingoh99 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +                updatedTags, updatedOrders);
```suggestion
        return new Person(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedCompany, updatedIsFavourite, updatedTags, updatedOrders);
```

2024-03-16 13:16 UTC, gavingoh99 approved these changes
LGTM! Nice handling of the issues raised.

2024-03-16 13:40 UTC, merged